name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7
      
    - name: set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run ktlint
      run: ./gradlew ktlintCheck

    - name: Run detekt
      run: ./gradlew detekt
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest

    - name: Assemble Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v7
      with:
        name: budget-brewer-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
